[package]
name = "stock_pilot"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2", features = ["sqlite", "r2d2"] }
serde = { version = "1.0.228", features = [ "derive" ]}
actix-files = "0.6.9"
actix-web = "4"
dotenvy = "0.15"
r2d2 = "0.8.10"
tera = "1"
